require:
- rubocop-performance
- rubocop-rake
- rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
  - 'db/**/*'
  - 'config/**/*'
  - 'script/**/*'
  - 'bin/**/*'
  - .pryrc

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - local

Gemspec/RequireMFA:
  Enabled: false

Style:
  Enabled: false

Layout/LineLength:
  Max: 180

Layout/HashAlignment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
