require:
- rubocop-factory_bot
- rubocop-capybara

plugins:
- rubocop-performance
- rubocop-rake
- rubocop-rails
- rubocop-thread_safety

AllCops:
  NewCops: enable
  Exclude:
  - 'db/**/*'
  - 'config/**/*'
  - 'script/**/*'
  - 'bin/**/*'
  - .pryrc
  - 'storage/**/*'
  - 'log/**/*'
  - 'tmp/**/*'
  - 'vendor/**/*'

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - local

Gemspec/RequireMFA:
  Enabled: false

Style:
  Enabled: false

Layout/LineLength:
  Max: 280

Layout/HashAlignment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false
