name: Publish coming soon page
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    name: Deploy GitHub pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.${GITHUB_DOMAIN:-"github.com"}"

      - run: |
          cp public/* .
          mv coming_soon.html index.html
          git checkout gh-pages
          git add . --all
          git commit -m 'updated'
          git push
